fixes for feedback from qa
EyeSeeTea/sharing-settings-app-dev pull request #11
Opened 2022-12-09 19:20 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/1mufxfj

### :memo: Implementation

### :art: Screenshots

### :fire: Testing

2024-04-25 08:30 UTC, anagperal commented on src/webapp/pages/bulk-apply/steps/AccessStep.tsx
> +                        onChange={e =>
This change works, but onChange function returns (event: React.ChangeEvent<HTMLInputElement>, isReplacingExistingSharings: boolean), so it's better to maintain this logic:

```typescript
      onChange={(event: React.ChangeEvent<HTMLInputElement>, isReplacingExistingSharings: boolean) =>
                            isReplacingExistingSharings
                                ? setDialogOpen(true)
                                : setReplaceStragegy(event, isReplacingExistingSharings)
                        }
```

2024-04-25 08:42 UTC, anagperal commented on src/webapp/pages/bulk-apply/steps/ListDependenciesStep.tsx
> +            <Button
Add same margin-left that the Dropdown has to make it look better

2024-04-25 08:46 UTC, anagperal commented on src/webapp/pages/bulk-apply/steps/SummaryApplyStep.tsx
> +                onSave={applySharingSync}
onSave execute close this dialog and applySharingSync (in a useCallback hook)

2024-04-25 08:48 UTC, anagperal approved these changes

2024-04-25 08:53 UTC, anagperal requested changes
thanks @deeonwuli ! Apart from the comments in the code, accoding to taks in https://app.clickup.com/t/1mufxfj
- some task in the checklist are not done. I don't know if it's because it has to be that way and there is no need for them to be made
- Add pagination to bottom of table (misc, this is normal behavior everywhere) and Selection reloads order and moves (ENTO- vs ENTO -) [See GIF ss-1] are not implemented

And according with task https://app.clickup.com/t/1crue0m Warnings page with Users/Groups assigned to parent not assigned to children (Both meta and data shared) is not implemented (I don't know if it's because it has to be that way and there is no need)

2024-04-26 09:34 UTC, MiquelAdell commented
@anagperal sorry because I should have access to that information but… What checklist are you referencing in your previous comment? 
As I want to release a version of this app Monday at the latest if the functionality for "Warnings page with Users/Groups assigned to parent not assigned to children" is not present I will create a new task for that and merge the current changes.
Most provably the same will be true for this task in the checklist.

TL;DR: finish started tasks that are failing, I'll create new tasks for pending code

2024-04-26 10:29 UTC, anagperal commented
> @anagperal sorry because I should have access to that information but… What checklist are you referencing in your previous comment? As I want to release a version of this app Monday at the latest if the functionality for "Warnings page with Users/Groups assigned to parent not assigned to children" is not present I will create a new task for that and merge the current changes. Most provably the same will be true for this task in the checklist.
> 
> TL;DR: finish started tasks that are failing, I'll create new tasks for pending code

@MiquelAdell this is the checklist:
![image](https://github.com/EyeSeeTea/sharing-settings-app-dev/assets/49402898/ec650318-c4be-48ca-a5f4-f9e434a72b98)

It's in actions item tab in https://app.clickup.com/t/1mufxfj

2024-04-26 11:23 UTC, MiquelAdell commented
Thanks @anagperal I've moved both action items to their own tasks. As well as "Add pagination to bottom of table…" to a new task.

@deeonwuli I'm not sure if this task is blocked by something or we just need to fix some bug regarding it:
https://app.clickup.com/t/1crue0m

2024-04-29 05:56 UTC, anagperal requested changes
This comment is not solved yet: https://github.com/EyeSeeTea/sharing-settings-app-dev/pull/11#discussion_r1579111679

2024-04-29 07:18 UTC, anagperal approved these changes
@deeonwuli code looks good, thanks!

2024-04-29 07:32 UTC, merged