2.38 compatibility test fixes
EyeSeeTea/sharing-settings-app-dev pull request #12
Opened 2022-12-21 12:09 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/3k6naef

### :memo: Implementation

### :art: Screenshots

### :fire: Testing

2023-01-11 21:51 UTC, nshandra approved these changes
Looks good.

In my test between DHIS v2.36 and 2.38 the metadata POST response format changed from:
```
{
    "importParams": {
        "userOverrideMode": "NONE",
        "importMode": "COMMIT",
        "identifier": "UID",
        "preheatMode": "REFERENCE",
        "importStrategy": "CREATE_AND_UPDATE",
        "atomicMode": "ALL",
        "mergeMode": "REPLACE",
        "flushMode": "AUTO",
        "skipSharing": false,
        "skipTranslation": false,
        "skipValidation": false,
        "metadataSyncImport": false,
        "firstRowIsHeader": true,
        "username": "admin"
    },
    "status": "OK",
    "stats": {
        "created": 0,
        "updated": 0,
        "deleted": 0,
        "ignored": 0,
        "total": 0
    },
    "typeReports": []
}
```
to:
```
{
    "httpStatus": "OK",
    "httpStatusCode": 200,
    "status": "OK",
    "response": {
        "responseType": "ImportReport",
        "status": "OK",
        "stats": {
            "created": 0,
            "updated": 0,
            "deleted": 0,
            "ignored": 0,
            "total": 0
        },
        "typeReports": []
    }
}
```
So, the new interface allows using either version.

2024-04-24 06:51 UTC, anagperal commented
I'm not able to update any sharing settings (tested dashboard, program and dataset in https://dev.eyeseetea.com/who-dev-238, https://dev.eyeseetea.com/play and in https://play.dhis2.org/2.38.6). In any api response publicAccess, userAccesses or userGroupAccesses it's obtained. Because of that in ApplySharingSettingsUseCase any payload is send to update, we always send in the POST:
```
{
  "dataSets": [],
  "categoryCombos": [],
  "categoryOptionCombos": [],
  "categories": [],
  "categoryOptions": [],
  "dataElements": []
}
```
This could be because of this: https://docs.dhis2.org/es_419/develop/using-the-api/dhis-core-version-239/sharing.html#new-sharing-object. Now we have the sharing object so we need to add this logic too


![image](https://github.com/EyeSeeTea/sharing-settings-app-dev/assets/49402898/6b13dfb0-4860-4d73-af0f-2f66fb8d580e)

2024-04-25 07:30 UTC, anagperal commented on src/domain/entities/MetadataItem.ts
> +    sharing: {
Create here a new type:

```typescript
export type Sharing = {
    sharing: SharingObject;
};

export type SharingObject = {
    userGroups: Record<string, SharingSetting>;
    users: Record<string, SharingSetting>;
    public: string;
};

export type MetadataItem = Ref & Sharing & SharedObject & { [key: string]: any | undefined };
```

2024-04-25 07:36 UTC, anagperal commented on src/domain/usecases/metadata/ApplySharingSettingsUseCase.ts
>      private updateSharingSettings(item: MetadataItem, sharings: SharedObject, replace: boolean): MetadataItem {
You need also to update `userGroups`, `users` and `public` inside new `sharing` object in every item (not only `publicAccess`, `userAccesses` and `userGroupAccesses` that are ok). In addition, you need to apply the function `assertValidSharingSettings` to `acces`  property inside properties in the new `sharing` object

2024-04-25 07:37 UTC, anagperal requested changes
thanks @deeonwuli ! I've added some comments (functional testing and code checked)

2024-04-25 08:10 UTC, anagperal commented
In addition to this comments, in SelectMetadataStep and in ListDependenciesStep components when rows are created add this to each item for displaying in the table the info in the columns publicAccess, userAccesses, userGroupAccesses
```typescript
publicAccess: item.publicAccess ?? item.sharing.public,
userGroupAccesses: item.userGroupAccesses ?? Object.values(item.sharing.userGroups),
userAccesses: item.userAccesses ?? Object.values(item.sharing.users),
```

2024-04-25 09:16 UTC, anagperal commented on src/domain/entities/MetadataItem.ts
> +    return item.id && item.sharing;
To make it retro-compatible:  item should have or sharing object or the other properties

2024-04-26 06:06 UTC, anagperal commented on src/domain/entities/SharedObject.ts
> +import { SharingRule } from "@eyeseetea/d2-ui-components";
You never have to take entities of your domain from outside, instead create a new one:
```typescript
export type SharingSetting = { id: Id; displayName: string; access: string; name: string };

```

2024-04-26 06:08 UTC, anagperal commented
thanks @deeonwuli for all the fixes! It works :tada:! Only one comment about `SharingSetting` entity and that's all!
![Screenshot from 2024-04-26 08-02-55](https://github.com/EyeSeeTea/sharing-settings-app-dev/assets/49402898/f86abb18-1b6c-4658-ae4b-d40378eff59b)

2024-04-26 07:55 UTC, nshandra commented
Given the review from Ana i will remove myself from the reviewers.

2024-04-26 10:31 UTC, anagperal approved these changes
@deeonwuli thanks!!

2024-04-29 07:32 UTC, merged